"""
Cross-model, cross-dataset report: tables + graphs from every trace on disk.

    uv run --with matplotlib --with numpy python fuse/report.py     # writes ../results/

Reads vlm_critic_out*/<model>/*.json, sam3_out/*/*.json, geometric_out/*.json and produces:
  results/README.md                 all tables (per-episode verdicts, per-model summary)
  results/eva_roc.png               ROC per criterion on the labelled slice
  results/eva_scores_by_label.png   p_done_late by ground-truth label, per model
  results/prevalence.png            success/failure counts per dataset x model
  results/agreement.png             pairwise model agreement on human sets
  results/traces_<dataset>.png      p(done) traces per episode, one panel per model
Numpy + matplotlib only.
"""

import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from fuse import auroc, label_of, seg_features, vlm_features  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT.parent / "results"
OUT.mkdir(exist_ok=True)

DATASETS = {
    # name: (vlm dir, seg dir, geo dir or None, description)
    "eva":   ("vlm_critic_out",       "sam3_out/episodes", "geometric_out",
              "20 eva_bimanual robot episodes, labelled 10/10"),
    # 3 fps VLM traces (stride 10 on the 30 fps source) are canonical; the 1 fps parquet run
    # lives in vlm_critic_out_cup50/ and is reported separately as the sampling-rate check.
    "cup50": ("vlm_critic_out_cup50_3fps", "sam3_out/cup50", None,
              "human cup-on-saucer clips (somundane/egoverse-cup50), unlabelled, VLMs at 3 fps"),
    "aria":  ("vlm_critic_out_aria",  "sam3_out/aria",     None,
              "human egocentric cup-on-saucer episodes (aria), unlabelled"),
}
MODELS = ["qwen", "paligemma", "cosmos"]
# Which trace statistic tags an episode. `late` = mean p(done) over the last quarter of
# frames — right when the episode ends on the goal state (short clips, fixed camera). `max`
# = peak p(done) — for long egocentric episodes where the person looks away after placing
# the cup, so the goal state is not in view at the end. Stated per dataset, not tuned.
TAG_STAT = {"eva": "late", "cup50": "late", "aria": "max"}
NICE = {"qwen": "Qwen3-VL-8B", "paligemma": "PaliGemma2-3B", "cosmos": "Cosmos-Reason2-8B"}


def load(d):
    d = ROOT / d
    return {p.stem: json.loads(p.read_text()) for p in sorted(d.glob("*.json"))} if d.is_dir() else {}


def collect():
    rows = []  # one per (dataset, model, episode)
    for ds, (vdir, sdir, gdir, _) in DATASETS.items():
        seg = load(sdir)
        for m in MODELS:
            vlm = load(f"{vdir}/{m}")
            if not vlm:
                continue
            # Fixed 0.5: with the goal-state question p(done) spans 0-1 and is comparable
            # across episodes. A per-set median would force every set to 50/50 tags, which
            # is meaningless as a prevalence estimate on unlabelled data.
            thresh = 0.5
            for ep, rec in vlm.items():
                vf = vlm_features(rec)
                if not vf:
                    continue
                sf = seg_features(seg.get(ep, {})) if ep in seg else {}
                stat = vf["p_done_max"] if TAG_STAT.get(ds) == "max" else vf["p_done_late"]
                rows.append({
                    "dataset": ds, "model": m, "episode": ep, "label": label_of(rec),
                    "p_done_late": vf["p_done_late"], "p_done_max": vf["p_done_max"],
                    "stat": stat, "stat_name": TAG_STAT.get(ds, "late"),
                    "trace": rec["p_yes"], "thresh": thresh,
                    "pred": "success" if stat > thresh else "failure",
                    "pred_late": "success" if vf["p_done_late"] > thresh else "failure",
                    "pred_max": "success" if vf["p_done_max"] > thresh else "failure",
                    "seg_score": sf.get("seg_score"),
                    "top_tokens": rec.get("last_frame_top_tokens"),
                })
    return rows


def md_table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    for r in rows:
        out.append("| " + " | ".join(str(x) for x in r) + " |")
    return "\n".join(out)


def main():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    rows = collect()
    if not rows:
        sys.exit("no traces found")
    md = ["# Results\n", "Generated by `fuse/report.py` from the traces on disk.\n"]

    # ---------------- per-model summary per dataset -------------------------------------
    md.append("## Per-model summary\n")
    summ = []
    for ds in DATASETS:
        for m in MODELS:
            sub = [r for r in rows if r["dataset"] == ds and r["model"] == m]
            if not sub:
                continue
            n = len(sub)
            ns = sum(r["pred"] == "success" for r in sub)
            lab = [r for r in sub if r["label"]]
            if lab:
                y = [1 if r["label"] == "success" else 0 for r in lab]
                acc = np.mean([r["pred"] == r["label"] for r in lab])
                au = auroc([r["p_done_late"] for r in lab], y)
                acc_s, au_s = f"{acc:.2f}", f"{au:.2f}"
            else:
                acc_s = au_s = "—"
            ns_late = sum(r["pred_late"] == "success" for r in sub)
            ns_max = sum(r["pred_max"] == "success" for r in sub)
            summ.append([ds, NICE[m], n, sub[0]["stat_name"], ns, n - ns, f"{100*(n-ns)/n:.0f}%",
                         f"{ns_late}/{n}", f"{ns_max}/{n}", acc_s, au_s])
    md.append(md_table(["dataset", "model", "n", "tag stat", "tagged success", "tagged failure",
                        "failure prevalence", "success @late", "success @max", "accuracy", "AUROC"], summ))
    md.append("\nAccuracy/AUROC only where ground truth exists (eva); AUROC is threshold-free. "
              "Tag = stat ≥ 0.5. `late` = mean p(done) over the last quarter of frames; `max` = "
              "peak p(done). **aria uses `max`**: those are 80–140 s egocentric episodes and the "
              "person looks away after placing the cup, so the goal state is not in view at the "
              "end — `late` reads No for everything (0/8 under Qwen and Cosmos). Both counts are "
              "shown for every set so the choice is visible, not hidden.\n")

    # ---------------- SEG-only prevalence (cup50 has 50 SEG traces) ---------------------
    for ds, (_, sdir, _, _) in DATASETS.items():
        seg = load(sdir)
        if not seg:
            continue
        scores = [seg_features(v).get("seg_score") for v in seg.values()]
        scores = [s for s in scores if s is not None]
        if scores:
            ns = sum(s >= 0.5 for s in scores)
            md.append(f"**SEG-only ({ds}, {len(scores)} episodes):** cup-on-saucer ≥ 0.5 → "
                      f"{ns} success / {len(scores)-ns} failure "
                      f"({100*(len(scores)-ns)/len(scores):.0f}% failure prevalence).\n")

    # ---------------- per-episode verdicts --------------------------------------------
    md.append("## Per-episode verdicts\n")
    for ds in DATASETS:
        sub = [r for r in rows if r["dataset"] == ds]
        if not sub:
            continue
        eps = sorted({r["episode"] for r in sub})
        models_here = [m for m in MODELS if any(r["model"] == m for r in sub)]
        md.append(f"### {ds} — {DATASETS[ds][3]}\n")
        hdr = ["episode", "label"] + [f"{NICE[m]} ({TAG_STAT.get(ds,'late')})" for m in models_here] + ["SEG", "consensus"]
        body = []
        for ep in eps:
            r0 = next(r for r in sub if r["episode"] == ep)
            cells = [ep, r0["label"] or "—"]
            preds = []
            for m in models_here:
                r = next((r for r in sub if r["episode"] == ep and r["model"] == m), None)
                if r:
                    preds.append(r["pred"])
                    cells.append(f"{'✅' if r['pred']=='success' else '❌'} {r['stat']:.2f} (late {r['p_done_late']:.2f} / max {r['p_done_max']:.2f})")
                else:
                    cells.append("—")
            seg_s = r0.get("seg_score")
            if seg_s is not None:
                preds.append("success" if seg_s >= 0.5 else "failure")
                cells.append(f"{'✅' if seg_s>=0.5 else '❌'} {seg_s:.2f}")
            else:
                cells.append("—")
            if preds:
                ns = preds.count("success")
                cells.append(f"{'success' if ns > len(preds)/2 else 'failure' if ns < len(preds)/2 else 'split'} ({ns}/{len(preds)})")
            else:
                cells.append("—")
            body.append(cells)
        md.append(md_table(hdr, body) + "\n")

    # ---------------- what the models actually said (top tokens) -----------------------
    md.append("## What the model wanted to say (top-5 first tokens, last frame)\n")
    for ds in DATASETS:
        for m in MODELS:
            ex = next((r for r in rows if r["dataset"] == ds and r["model"] == m and r["top_tokens"]), None)
            if ex:
                md.append(f"- **{ds} / {NICE[m]}** ({ex['episode']}): "
                          + ", ".join(f"`{t}`={p}" for t, p in ex["top_tokens"]))
    md.append("")

    # ---------------- graphs -----------------------------------------------------------
    colors = {"qwen": "#1982c4", "paligemma": "#8ac926", "cosmos": "#ff595e", "seg": "#ffca3a"}

    # ROC on eva
    eva = [r for r in rows if r["dataset"] == "eva" and r["label"]]
    if eva:
        fig, ax = plt.subplots(figsize=(5, 5))
        for m in MODELS:
            sub = [r for r in eva if r["model"] == m]
            if not sub:
                continue
            y = np.array([1 if r["label"] == "success" else 0 for r in sub])
            s = np.array([r["p_done_late"] for r in sub])
            fpr, tpr = roc(s, y)
            ax.plot(fpr, tpr, color=colors[m], lw=2, label=f"{NICE[m]} (AUROC {auroc(list(s), list(y)):.2f})")
        seg = load(DATASETS["eva"][1])
        segrows = [(seg_features(v).get("seg_score"), label_of(v)) for v in seg.values()]
        segrows = [(s, l) for s, l in segrows if s is not None and l]
        if segrows:
            s = np.array([x for x, _ in segrows]); y = np.array([1 if l == "success" else 0 for _, l in segrows])
            fpr, tpr = roc(s, y)
            ax.plot(fpr, tpr, color=colors["seg"], lw=2, ls="--", label=f"SAM 3 cup-on-saucer (AUROC {auroc(list(s), list(y)):.2f})")
        ax.plot([0, 1], [0, 1], color="#999", lw=1, ls=":")
        ax.set_xlabel("false positive rate"); ax.set_ylabel("true positive rate")
        ax.set_title("eva labelled slice (10 success / 10 failure)")
        ax.legend(fontsize=8, loc="lower right"); ax.set_aspect("equal")
        fig.tight_layout(); fig.savefig(OUT / "eva_roc.png", dpi=150); plt.close(fig)

        # scores by label
        fig, ax = plt.subplots(figsize=(6, 3.5))
        xs = 0
        ticks, tlabels = [], []
        for m in MODELS:
            sub = [r for r in eva if r["model"] == m]
            if not sub:
                continue
            for lab, off in (("failure", -0.18), ("success", 0.18)):
                v = [r["p_done_late"] for r in sub if r["label"] == lab]
                jitter = (np.random.RandomState(0).rand(len(v)) - 0.5) * 0.15
                ax.scatter(np.full(len(v), xs + off) + jitter, v, s=28,
                           color=colors[m], alpha=0.85, marker="o" if lab == "success" else "x")
            ticks.append(xs); tlabels.append(NICE[m]); xs += 1
        ax.set_xticks(ticks); ax.set_xticklabels(tlabels)
        ax.set_ylabel("p(done), last quarter"); ax.set_title("eva: x = failure, o = success")
        fig.tight_layout(); fig.savefig(OUT / "eva_scores_by_label.png", dpi=150); plt.close(fig)

    # prevalence bars
    fig, ax = plt.subplots(figsize=(7, 3.5))
    labels, succ, fail, cols = [], [], [], []
    for ds in DATASETS:
        for m in MODELS:
            sub = [r for r in rows if r["dataset"] == ds and r["model"] == m]
            if not sub:
                continue
            labels.append(f"{ds}\n{NICE[m]}")
            ns = sum(r["pred"] == "success" for r in sub)
            succ.append(ns); fail.append(len(sub) - ns); cols.append(colors[m])
    x = np.arange(len(labels))
    ax.bar(x, succ, color="#8ac926", label="tagged success")
    ax.bar(x, fail, bottom=succ, color="#ff595e", label="tagged failure")
    ax.set_xticks(x); ax.set_xticklabels(labels, fontsize=7)
    ax.set_ylabel("episodes"); ax.set_title("Tags per dataset × model (p_done_late ≥ 0.5)")
    ax.legend(fontsize=8)
    fig.tight_layout(); fig.savefig(OUT / "prevalence.png", dpi=150); plt.close(fig)

    # agreement heatmap on human sets
    for ds in ("cup50", "aria"):
        sub = [r for r in rows if r["dataset"] == ds]
        ms = [m for m in MODELS if any(r["model"] == m for r in sub)]
        if len(ms) < 2:
            continue
        eps = sorted({r["episode"] for r in sub})
        P = {m: {r["episode"]: r["pred"] for r in sub if r["model"] == m} for m in ms}
        A = np.zeros((len(ms), len(ms)))
        for i, a in enumerate(ms):
            for j, b in enumerate(ms):
                common = [e for e in eps if e in P[a] and e in P[b]]
                A[i, j] = np.mean([P[a][e] == P[b][e] for e in common]) if common else np.nan
        fig, ax = plt.subplots(figsize=(3.6, 3.2))
        im = ax.imshow(A, vmin=0, vmax=1, cmap="Blues")
        ax.set_xticks(range(len(ms))); ax.set_yticks(range(len(ms)))
        ax.set_xticklabels([NICE[m] for m in ms], rotation=30, ha="right", fontsize=7)
        ax.set_yticklabels([NICE[m] for m in ms], fontsize=7)
        for i in range(len(ms)):
            for j in range(len(ms)):
                ax.text(j, i, f"{A[i,j]:.2f}", ha="center", va="center", fontsize=8,
                        color="white" if A[i, j] > 0.6 else "black")
        ax.set_title(f"{ds}: tag agreement", fontsize=9)
        fig.tight_layout(); fig.savefig(OUT / f"agreement_{ds}.png", dpi=150); plt.close(fig)

    # traces per dataset
    for ds in DATASETS:
        sub = [r for r in rows if r["dataset"] == ds]
        ms = [m for m in MODELS if any(r["model"] == m for r in sub)]
        if not ms:
            continue
        fig, axes = plt.subplots(1, len(ms), figsize=(4.2 * len(ms), 3.2), squeeze=False)
        for ax, m in zip(axes[0], ms):
            for r in [r for r in sub if r["model"] == m]:
                t = np.array(r["trace"]); xx = np.linspace(0, 1, len(t))
                c = "#8ac926" if (r["label"] or r["pred"]) == "success" else "#ff595e"
                ax.plot(xx, t, color=c, alpha=0.7, lw=1.2)
            ax.axhline(0.5, color="#999", lw=0.8, ls=":")
            ax.set_ylim(-0.02, 1.02); ax.set_title(NICE[m], fontsize=9)
            ax.set_xlabel("episode progress"); ax.set_ylabel("p(done)")
        note = "colour = ground truth" if ds == "eva" else "colour = model's own tag"
        fig.suptitle(f"{ds}: confidence traces ({note})", fontsize=10)
        fig.tight_layout(); fig.savefig(OUT / f"traces_{ds}.png", dpi=150); plt.close(fig)

    md.append("## Graphs\n")
    for f in sorted(OUT.glob("*.png")):
        md.append(f"### {f.stem}\n\n![{f.stem}]({f.name})\n")
    (OUT / "README.md").write_text("\n".join(md) + "\n")
    print("\n".join(md[:40]))
    print(f"\n✓ wrote {OUT}/README.md and {len(list(OUT.glob('*.png')))} graphs")


def roc(scores, y):
    order = np.argsort(-scores)
    s, yy = scores[order], y[order]
    P, N = yy.sum(), len(yy) - yy.sum()
    tpr, fpr = [0.0], [0.0]
    tp = fp = 0
    for i in range(len(s)):
        if yy[i]:
            tp += 1
        else:
            fp += 1
        tpr.append(tp / max(P, 1)); fpr.append(fp / max(N, 1))
    return np.array(fpr), np.array(tpr)


if __name__ == "__main__":
    main()
